### DISCUSSION TITLE
clusterpedia-synchro ClusterRole breadth?

### DISCUSSION THREAD

**Discussion by TNonet** [clusterpedia-io/clusterpedia#656] [General]
I wanted to double-check my understanding of which rules the `clusterpedia-synchro` ClusterRole actually needs.
The current [example](https://github.com/clusterpedia-io/clusterpedia/blob/main/examples/clusterpedia_synchro_rbac.yaml) has basically `*` perms. 

However, I am a just syncing pods with ClusterPedia, can the role be restricted to just the following? 

```yml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterpedia-synchro
rules:
- apiGroups:
  - '*'
  resources:
  - 'pods'
  verbs:
  - 'get'
  - 'watch'
  - 'list'
```
