### ISSUE TITLE
support custom resource

### ISSUE THREAD

**Issue by Iceber** [clusterpedia-io/clusterpedia#14]
For the synchronization of custom resources is developed in two stages：

1. The default collection policy, where the user specifies the version to be synchronized,If no version is specified, then the top three versions of the priority order in the member cluster will be synchronized by default. https://github.com/clusterpedia-io/clusterpedia/pull/10
2. The `clustersynchro manager` reconciles the `sync version` and `storage version` that should be synchronized by the member cluster

**Comment by Iceber** [comment]
The default policy stores redundant data for multiple versions of custom resources.

In the next stage, the versions of custom resources in different clusters are reconciled in the `clustersynchro manager` by watching for the `CRD` resources.

If there is an intersection between the versions of custom resources between clusters and the conversion strategy is `None, then only one version needs to be synchronized in the cluster and saved as the same version.

if the conversion strategy for a custom resource between clusters is `Webhook`, then it falls back to the [default synchronization policy](https://github.com/clusterpedia-io/clusterpedia/pull/10#issue-1071840038)

---
We may add a custom resource `MultiClusterCustomResourceDefinition` to the main cluster to reconcile the crd versions of multiple clusters.

The `MultiClusterCustomResourceDefinition` does not store schema information about the resource versions, but rather what versions should be currently supported and what the stored versions of those versions should be. 
Similarly `MultiClusterCustomResourceDefinition` can tell the `clusterpedia apiserver` how to provide the API for the resource.

**Comment by Iceber** [comment]
For the `ResourceColumnDefinition` of the custom resource used for the Table output, a new CRD will be provided to allow the user to customize the Table output of `any resource`.(Roadmap)

ResourceColumnDefinition for CRD:
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
spec:
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.apiserverURL
      name: APIServer URL
      type: string
    - jsonPath: .status.version
      name: Version
      type: string
    - jsonPath: .status.conditions[?(@.type == 'Ready')].reason
      name: Status
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:

```
