### ISSUE TITLE
Support wildcard (like "*") for resources to sync

### ISSUE THREAD

**Issue by 27149chen** [clusterpedia-io/clusterpedia#168]
### What would you like to be added?

Support wildcard (like "*") for resources to sync, in the following format:
```yaml
# all resources in all groups
syncResources:
- group: "*"
  resources:
  - "*"
  ```

```yaml
# all resources in group apps
syncResources:
- group: "apps"
  resources:
  - "*"
  ```

### Why is this needed?

we need to list all resources in a cluster dynamically (the resource types might be changing)
