### ISSUE TITLE
Require explicit setup-go installation step prior to using the golangci-action

### ISSUE THREAD

**Issue by Iceber** [clusterpedia-io/clusterpedia#365]
### What would you like to be added?

https://github.com/golangci/golangci-lint-action#compatibility
> v3.0.0+ requires explicit setup-go installation step prior to using this action: uses: actions/setup-go@v3. The skip-go-installation option has been removed.

Run `setup-go action` before the golangci-action.

change:
https://github.com/clusterpedia-io/clusterpedia/blob/99d1631bca84b5680012786cba1d4e36428d1d1d/.github/workflows/ci.yml#L5-L14
to
```yaml
jobs:
  golangci:
    name: Lint with golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: golangci/golangci-lint-action@v3
         with:
           version: v1.46.2
```

### Why is this needed?

https://github.com/golangci/golangci-lint-action#compatibility
