### ISSUE TITLE
When running on k8s 1.18.6, clusterpedia failed to run

### ISSUE THREAD

**Issue by panpan0000** [clusterpedia-io/clusterpedia#381]
### What happened?

error message:
<img width="1252" alt="企业微信截图_4378897b-7dc5-40e5-8033-78942644161b" src="https://user-images.githubusercontent.com/14049268/191458416-a54a39aa-6b0f-4138-972c-48f60fd5e041.png">

### What did you expect to happen?

it run well

### How can we reproduce it (as minimally and precisely as possible)?

1.18

### Clusterpedia Version

<details>

```console
# replace the pod name of clusterpedia apiserver
$ kubectl -n clusterpedia-system exec {clusterpedia-apiserver-pod-name} -- apiserver --version=raw
# paste output here

# replace the pod name of clusterpedia clustersynchro-manager
$ kubectl -n clusterpedia-system exec {clustersynchro-manager-pod-name} -- clustersynchro-manager --version=raw
# paste output here
```

</details>

### Host Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

**Comment by Iceber** [comment]
This is because the front-proxy-ca.crt used by your kube apiserver is using SHA1, it is recommended to recreate front-proxy-client.crt, SHA1 has security issues.
```yaml
spec:
  containers:
  - command:
    - kube-apiserver
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
```

golang has rejected SHA1 since 1.18 https://github.com/golang/go/issues/41682, of course it is possible to use the environment variable `GODEBUG=x509sha1=1` to allow sha1 certificates, but this is still insecure.

However, to be compatible with more user scenarios, we will add a value to helm to help users configure the environment variable `GODEBUG=x509sha1=1`.
