### ISSUE TITLE
Compatible with front-proxy-client.crt created with SHA1

### ISSUE THREAD

**Issue by Iceber** [clusterpedia-io/clusterpedia#385]
This is because the front-proxy-client.crt used by your kube-apiserver is using SHA1, it is recommended to recreate front-proxy-client.crt, SHA1 has security issues.
```yaml
spec:
  containers:
  - command:
    - kube-apiserver
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
```

golang has rejected SHA1 since 1.18 https://github.com/golang/go/issues/41682, of course it is possible to use the environment variable `GODEBUG=x509sha1=1` to allow sha1 certificates, but this is still insecure.

However, to be compatible with more user scenarios, we will add a value to helm to help users configure the environment variable `GODEBUG=x509sha1=1`.

_Originally posted by @Iceber in https://github.com/clusterpedia-io/clusterpedia/issues/381#issuecomment-1254543799_
