### ISSUE TITLE
support for pruning `manageFields` and `last-applied-configuration` fields

### ISSUE THREAD

**Issue by Iceber** [clusterpedia-io/clusterpedia#4]
`Server-Side Apply` stores field management in the `manageFields`, which may not be useful during resource search.
This field needs to be pruned according to the user's needs.

The ` kubectl.kubernetes.io/last-applied-configuration` annotation also requires a feature gate to be provide  to prune.
```yaml
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"cluster-autoscaler"},"name":"poc-autoscaler","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"cluster-autoscaler"}},"template":{"metadata":{"labels":{"app":"cluster-autoscaler"}},"spec":{"containers":[{"args":["--cloud-provider=clusterapi","--kubeconfig=/etc/kubeconfig/value","--clusterapi-cloud-config-authoritative","--node-group-auto-discovery=clusterapi:clusterName=poc"],"command":["/cluster-autoscaler"],"image":"daocloud.io/daocloud/cluster-autoscaler:v1.20.1","name":"cluster-autoscaler","volumeMounts":[{"mountPath":"/etc/kubeconfig","name":"kubeconfig"}]}],"serviceAccountName":"cluster-autoscaler-management","terminationGracePeriodSeconds":10,"tolerations":[{"effect":"NoSchedule","key":"node-role.kubernetes.io/master"}],"volumes":[{"name":"kubeconfig","secret":{"secretName":"poc-kubeconfig"}}]}}}}
```
