### ISSUE TITLE
When list-watch suffer from network , some kind of warning or alert may be helpful

### ISSUE THREAD

**Issue by panpan0000** [clusterpedia-io/clusterpedia#487]
### What would you like to be added?

If there's a CRD or a prometheus metrics which tell user the sync is outdate , it will be a direct signal and  helpful to drive the user to diagnostic the network problem directly,

### Why is this needed?

For example, when the outbound network bandwidth is full (especially the public cloud), or when the network condition is rather bad,  the list-watch will be out of sync , and the data will be out of date as well.

If there's a CRD or a prometheus metrics which tell user the sync is outdate , it will be a direct signal and  helpful to drive the user to diagnostic the network problem directly,

<img width="1414" alt="wecom-temp-1415769-c1208c0b8da0c34b131d043bbba58bd2" src="https://user-images.githubusercontent.com/14049268/215652294-80a1b522-9ba9-43fe-8e97-7731b7ac9149.png">

**Comment by Iceber** [comment]
This log just shows that the list took a long time, but eventually the list succeeded and started watching

pediacluster has a synchronization status field for the resource, which shows specific information when the resource synchronization stops or is abnormal
```yaml
status:
...
  syncResources:
  - group: apps
    resources:
    - kind: Deployment
      name: deployments
      namespaced: true
      syncConditions:
      - lastTransitionTime: "2023-01-10T09:46:55Z"
        status: Stop
        storageVersion: v1
        version: v1
```

We can add another state between list and watch, `Syncing` state means when the list finishes and watch starts, we can use `Listing` or other states when starting the list
