### ISSUE TITLE
If the resource field value is a numeric value, then the FieldSelector does not work

### ISSUE THREAD

**Issue by Iceber** [clusterpedia-io/clusterpedia#63]
Storage Component: `mysql`

```bash
kubectl --cluster clusterpedia get deploy --field-selector="status.availableReplicas==1" -A
```
The sql generated by the sql builder is
```sql
SELECT * FROM `resources` WHERE `group` = 'apps' AND `resource` = 'deployments' AND `version` = 'v1' AND cluster = 'test-cluster-2' AND namespace = 'default' AND \
     JSON_EXTRACT(`object`,'$."status"."availableReplicas"') == '1' LIMIT 500
```
In this case, only if the field value is the string `'1'`/`"1"` will be searched for.
For example, this will work:
```bash
kubectl --cluster pedia get deploy --field-selector="metadata.annotations['deployment.kubernetes.io/revision']=1" 
```
resources:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
```
