### ISSUE TITLE
update the status of the `pediacluster` if the creation of cluster synchro fails

### ISSUE THREAD

**Issue by Iceber** [clusterpedia-io/clusterpedia#8]
The `cluster synchro` of `pediacluster` may fail to be. created due to many reasons, such as network problems, or authentication configuration....

Clusterpedia need to update the specific information to pediacluster's Conditions
eg.
```yaml
status:
  conditions:
  - type: ClusterSynchro
     status: "False"
     reason: "InitialFailed"
     message: "some error message"
  - message: ""
    reason: Pending
    status: "False"
    type: Ready
```
