### ISSUE TITLE
Support for fetching cluster authentication information from other resources

### ISSUE THREAD

**Issue by Iceber** [clusterpedia-io/clusterpedia#94]
### What would you like to be added?

`PdiaCluster` can directly reference fields from existing resources for cluster validation.

eg.
```
spec:
  apiserver: https://10.6.100.100:6443
  caRef:
    apiVersion: v1
    kind: Configmap
    name: cluster-1
    fieldPath: ".data.ca"
```

### Why is this needed?

Currently we need to fill `caData`, `tokenData` and other information in the `PediaCluster`,
but often these information may already exist in other resources, 
it would be very convenient if we can get the authentication information by referring to the fields of these resources.
